### ISSUE TITLE
Trophy names are unreadable in white mode

### ISSUE THREAD

**Issue by ivan-developer-01** [JunLovin/JunLovin#2]
When I'm viewing GitHub in white mode, your Trophies show:

> ![screenshot](https://github.com/JunLovin/JunLovin/assets/127977316/92bd3dc5-896f-426e-9fa1-025afe61fa0f)

However when I'm viewing GitHub in dark mode it shows:

> ![screenshot 2](https://github.com/JunLovin/JunLovin/assets/127977316/cbb92aae-4e0c-4d4e-9364-1fc27292f7a0)

I think it's time to fix it to have compatibility with white mode.

**Comment by ivan-developer-01** [comment]
I've opened an pull request that fixes it depending on the media "(prefers-color-scheme: dark)" and using the `picture` tag.

**Comment by JunLovin** [comment]
Thank you so much!
